### ISSUE TITLE
Sonnet keeps using EOF format

### ISSUE THREAD

**Issue by 0xbrayo** [ErikBjare/gptme#331] opened 2024-12-12 20:31 UTC
Sonnet recently tries to write to files using some weird format like `cat << " code" >> EOF` I don't exactly remember the syntax that always makes the command fail(will edit with the correct format when it does it again). An update to the tools prompt could easily fix this.

**Comment by ErikBjare** [comment] 2024-12-12 22:39
Duplicate of https://github.com/ErikBjare/gptme/issues/108?

We could try to fix the shell tool, would be nice.

**Comment by Miyou** [comment] 2024-12-13 09:57
I had the same issue a few times

**Closed** 2024-12-15 19:28 UTC
